all: demo1 demo2 demo3-1 demo3-2 demo4

demo1: demo1.cpp
	g++ demo1.cpp -static-libgcc -static-libstdc++ -o demo1

demo2: demo2.cpp
	g++ demo2.cpp -static-libgcc -static-libstdc++ -o demo2

demo3-1: demo3-1.cpp
	g++ demo3-1.cpp -static-libgcc -static-libstdc++ -o demo3-1

demo3-2: demo3-2.cpp
	g++ demo3-2.cpp -static-libgcc -static-libstdc++ -o demo3-2

demo4: demo4.cpp
	g++ demo4.cpp -static-libgcc -static-libstdc++ -o demo4