all: demo1 demo2 demo3 demo4 demo5

demo1: demo1.cpp
	g++ demo1.cpp -static-libgcc -static-libstdc++ -o demo1

demo2: demo2.cpp
	g++ demo2.cpp -static-libgcc -static-libstdc++ -o demo2

demo3: demo3.cpp
	g++ demo3.cpp -static-libgcc -static-libstdc++ -o demo3

demo4: demo4.cpp
	g++ demo4.cpp -static-libgcc -static-libstdc++ -o demo4

demo5: demo5.cpp
	g++ demo5.cpp -static-libgcc -static-libstdc++ -o demo5
