seam_carving: seam_carving.cpp
	g++ seam_carving.cpp -o seam_carving.exe -static-libgcc -static-libstdc++ -I 'D:\\opencv\\build\\install\\include' -L 'D:\\opencv\\build\\install\\x64\\mingw\\lib' -lopencv_world470
